### ISSUE TITLE
[V8] The image doesn't change

### ISSUE THREAD

**Issue by sharkutz** [nedaszilinskas/Odoo-CMS-Variant-Pictures#1]
The main images changes when you select different images( colors) but the small images from the variant remains the same.
Is there a special setup?

**Comment by sharkutz** [comment]
The extra cost (price is not shown)?!

**Comment by nedaszilinskas** [comment]
Hello sharkutz,

Please clarify the issues you are having. Some screenshots would be nice.

I just did tests and it seems everything works fine. See screenshots:
![1](https://cloud.githubusercontent.com/assets/7509962/7154797/628fc62a-e362-11e4-834e-e1fb354a77ba.png)
![2](https://cloud.githubusercontent.com/assets/7509962/7154798/62963f0a-e362-11e4-9e6a-c95a18c290e1.png)
![3](https://cloud.githubusercontent.com/assets/7509962/7154799/629cad2c-e362-11e4-818a-f7c86e1b09d4.png)
![4](https://cloud.githubusercontent.com/assets/7509962/7154800/62a00dbe-e362-11e4-90af-88267ca0b758.png)

All tests done on default clean database + black iPad picture uploaded.

Nedas

**Comment by sharkutz** [comment]
hi,
Sorry for the late response.
You are right it works with the default odoo theme.
I'm using the Zap theme and it doesn't i tried to find you but nothing. The same with the TABS module ( the tabs are not visible when using the zap theme.
