### ISSUE TITLE
Problems when using ZAP theme

### ISSUE THREAD

**Issue by sharkutz** [nedaszilinskas/Odoo-CMS-Variant-Pictures#2]
hi,
Sorry for the late response.
You are right it works with the default odoo theme.
I'm using the Zap theme and it doesn't i tried to find you but nothing. The same with the TABS module ( the tabs are not visible when using the zap theme.

**Comment by nedaszilinskas** [comment]
Hello sharkutz,

This module was meant to be used on default themes.
I do not have a commercial themes and its sources are not public therefore I cannot test it.

Nedas
